In [1]:
import pandas as pd
import numpy as np

In [50]:
df = pd.read_csv('simulated_radar_data.csv')
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   object_type  3000 non-null   object 
 1   range        3000 non-null   float64
 2   velocity     3000 non-null   float64
 3   angle        3000 non-null   float64
 4   amplitude    3000 non-null   float64
dtypes: float64(4), object(1)
memory usage: 117.3+ KB


range     velocity        angle    amplitude
count  3000.000000  3000.000000  3000.000000  3000.000000
mean     25.013717     8.080323    11.819160     0.113737
std       4.087003     5.619280    14.426883     0.118753
min      18.990000     0.660000    -8.310000    -0.310000
25%      20.207500     1.330000    -4.352500     0.030000
50%      25.010000     8.000000    10.040000     0.110000
75%      29.812500    14.860000    29.402500     0.190000
max      30.940000    15.630000    33.280000     0.490000

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report

# Features and target
X = df[['range', 'velocity', 'angle', 'amplitude']]
y = df['object_type']

# Encode target labels
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_encoded, test_size=0.2, random_state=42
)

# Train MLP model
mlp = MLPClassifier(hidden_layer_sizes=(2,), activation="relu", solver="adam", max_iter=54, random_state=42)
mlp.fit(X_train, y_train)

# Predict and evaluate
y_pred = mlp.predict(X_test)
print(classification_report(y_test, y_pred, target_names=le.classes_))


              precision    recall  f1-score   support

        bird       1.00      1.00      1.00       201
         car       1.00      1.00      1.00       201
       human       1.00      1.00      1.00       198

    accuracy                           1.00       600
   macro avg       1.00      1.00      1.00       600
weighted avg       1.00      1.00      1.00       600



c:\Pyth\radarobj_detection\radarml\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:780: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (54) reached and the optimization hasn't converged yet.
  warnings.warn(


In [76]:
# Weights from input to hidden layer
input_to_hidden_weights = mlp.coefs_[0]      # shape: (4 features, 2 hidden neurons)
hidden_biases = mlp.intercepts_[0]           # shape: (2,)

# Weights from hidden to output layer
hidden_to_output_weights = mlp.coefs_[1]     # shape: (2 hidden neurons, 3 classes)
output_biases = mlp.intercepts_[1]           # shape: (3,)

print("Input to Hidden Weights:\n", input_to_hidden_weights)
print("Hidden Biases:\n", hidden_biases)

print("Hidden to Output Weights:\n", hidden_to_output_weights)
print("Output Biases:\n", output_biases)

Input to Hidden Weights:
 [[-0.66445356  1.59567296]
 [ 0.0582999   0.89286338]
 [-1.15400322 -1.0625286 ]
 [-0.50646296  0.72970407]]
Hidden Biases:
 [0.32990558 0.93513002]
Hidden to Output Weights:
 [[-1.18314046  0.44529352  1.36522833]
 [-1.1067273  -0.2497119  -1.11587357]]
Output Biases:
 [ 0.21743981 -0.54201412 -0.5477511 ]
